name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEVQA_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEVQA_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/sigof-facturador-web/browser s3://sigof-apps-web-facturador-devqa 
